### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ramjar420** [HrishikeshS123/Naruto-helper#1]
Hi, Im getting this error atm. I have no experience working with this. Would you mind helping me out?

Naruto-helper-main\node_modules\mongoose\lib\connection.js:689
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
          ^

MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (C:\Users\ramja\Desktop\Naruto-helper-main\node_modules\mongoose\lib\connection.js:689:11)
    at C:\Users\ramja\Desktop\Naruto-helper-main\node_modules\mongoose\lib\index.js:340:10
    at C:\Users\ramja\Desktop\Naruto-helper-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\ramja\Desktop\Naruto-helper-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (C:\Users\ramja\Desktop\Naruto-helper-main\node_modules\mongoose\lib\index.js:1140:10)
    at Mongoose.connect (C:\Users\ramja\Desktop\Naruto-helper-main\node_modules\mongoose\lib\index.js:339:20)
    at Object.<anonymous> (C:\Users\ramja\Desktop\Naruto-helper-main\index.js:14:10)

**Comment by Ramjar420** [comment]
lol loser

**Comment by NoClueWhoIAm** [comment]
yo true, fixed his problem in 10 minutes. Pretty good bot, thanks for sharing @HrishikeshS123

**Comment by HrishikeshS123** [comment]
Make sure the mongoose uri which you are providing in the connect() method is a string AND it is a mongoose uri.
